/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mo_livestream_rtmplive_MOLiveStreamSDK */

#ifndef _Included_mo_livestream_rtmplive_MOLiveStreamSDK
#define _Included_mo_livestream_rtmplive_MOLiveStreamSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mo_livestream_rtmplive_MOLiveStreamSDK
 * Method:    InitPublisher
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mo_livestream_rtmplive_MOLiveStreamSDK_InitPublisher
  (JNIEnv *, jobject);

/*
 * Class:     mo_livestream_rtmplive_MOLiveStreamSDK
 * Method:    DeinitPublisher
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mo_livestream_rtmplive_MOLiveStreamSDK_DeinitPublisher
  (JNIEnv *, jobject);

/*
 * Class:     mo_livestream_rtmplive_MOLiveStreamSDK
 * Method:    SetServerUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mo_livestream_rtmplive_MOLiveStreamSDK_SetServerUrl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mo_livestream_rtmplive_MOLiveStreamSDK
 * Method:    SetVideoEncode
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_mo_livestream_rtmplive_MOLiveStreamSDK_SetVideoEncode
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     mo_livestream_rtmplive_MOLiveStreamSDK
 * Method:    SetAudioEncode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_mo_livestream_rtmplive_MOLiveStreamSDK_SetAudioEncode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     mo_livestream_rtmplive_MOLiveStreamSDK
 * Method:    StartLive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mo_livestream_rtmplive_MOLiveStreamSDK_StartLive
  (JNIEnv *, jobject);

/*
 * Class:     mo_livestream_rtmplive_MOLiveStreamSDK
 * Method:    StopLive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mo_livestream_rtmplive_MOLiveStreamSDK_StopLive
  (JNIEnv *, jobject);

/*
 * Class:     mo_livestream_rtmplive_MOLiveStreamSDK
 * Method:    OnCaptureAudioData
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_mo_livestream_rtmplive_MOLiveStreamSDK_OnCaptureAudioData
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     mo_livestream_rtmplive_MOLiveStreamSDK
 * Method:    OnCaptureVideoData
 * Signature: ([BIIJII)I
 */
JNIEXPORT jint JNICALL Java_mo_livestream_rtmplive_MOLiveStreamSDK_OnCaptureVideoData
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong, jint);

/*
 * Class:     mo_livestream_rtmplive_MOLiveStreamSDK
 * Method:    ConvertYUVData
 * Signature: ([B[BI)I
 */
JNIEXPORT jint JNICALL Java_mo_livestream_rtmplive_MOLiveStreamSDK_ConvertYUVData
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
